# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

include: ["_pages"] #,"_data"]


title: "entroserv"
masthead_title: "entro<span style=font-weight:300;>py</span> serv<span style=font-weight:300;>ice</span>"
subtitle: "~ ein Beitrag zur Erhöhung der Entropie im Multiversum ~"
email: info@entroserv.de
description: >- # this means to ignore newlines until "baseurl:"
  Ideen, Projekte und Artikel rund um Technologie
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://entroserv.de" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

 
  #repository: TheTesla/thetesla.github.io
locale: de
  #locale: en

sass:
  style: compressed

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll 
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll_picture_tag

picture:
  source: /assets/images
  output: /assets/genimages
  defaults:
    dimension_attributes: true


#minimal_mistakes_skin: "air" #"default" ,  "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "contrast"

collections:
  articles:
    output: true
    permalink: /Artikel/:path/
  projects:
    output: true
    permalink: /Projekte/:path/
  ideas:
    output: true
    permalink: /Ideen/:path/




defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: false
      show_date: true
  # _articles
  - scope:
      path: ""
      type: articles
    values:
      layout: single
      author_profile: true
      related: false
      read_time: true
      share: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      related: false
      read_time: true
      share: true

      #search_provider: algolia

analytics: 
  provider: "custom"



breadcrumbs: true  # disabled by default

header:
  teaser: /assets/images/my-awesome-post-teaser.jpg


footer:
  links:
    - label: "Impressum"
      icon: "fa fa-fw fa-info"
      url: "/impressum"
    - label: "Datenschutz"
      icon: "fa fa-fw fa-shield-alt"
      url: "/privacy"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
